//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::DietaryPreferences;
use super::sea_orm_active_enums::Gender;
use super::sea_orm_active_enums::Role;
use super::sea_orm_active_enums::Sexuality;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
    pub mail: String,
    pub password: String,
    pub firstname: String,
    pub lastname: String,
    pub age: i32,
    pub gender: Gender,
    pub sexuality: Sexuality,
    #[sea_orm(column_type = "Text", nullable)]
    pub biography: Option<String>,
    pub location: Option<Json>,
    pub employer: Option<String>,
    pub school_grade: Option<String>,
    pub dietary_preferences: Option<DietaryPreferences>,
    pub company_role: Option<String>,
    pub role: Option<Role>,
    pub like: Option<Json>,
    pub like_by: Option<Json>,
    pub dislike: Option<Json>,
    pub dislike_by: Option<Json>,
    pub gallery: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
